---
title: "Finance Data Collection"
format: html
editor: visual
---

```{r}
library(dplyr)
library(priceR)
library(yfR)
```

```{r}
# P1: Stock price data
tickers <- c("PFE", "AZN", "JNJ", "MRNA", "1099.HK", "SVA", "NVAX", "6185.HK", "CASBF", "302440.KS")
first_date <- "2015-01-30"
last_date <- "2025-09-08"
cache_folder <- "../data"

df_yf <- yf_get(
  tickers = tickers,
  first_date = first_date,
  last_date = last_date,
  thresh_bad_data = 0,
  freq_data = "daily",
  do_complete_data = TRUE,
  do_cache = TRUE,
  cache_folder = cache_folder
)

print(df_yf)
```

```{r}
# P2: Currency conversion (forex) data
files <- paste0("../data/", list.files("../data"))
from_currency <- c("HKD", "KRW", "HKD", "GBP")

# loop through each file, onle 1-4 in non-USD
for (i in 1:4) {
  # read the data frame
  df <- readRDS(files[i])
  
  # convert all columns except the first
  df_usd <- df %>%
    mutate(across(
      .cols = -(1:2),
      .fns = ~ convert_currencies(
        price_start =.,
        from = from_currency[i],
        to = "USD",
        date = .data[["ref_date"]])
    ))
  
  # make new filename: e.g. USD_file1.rds
  new_name <- paste0("USD_", files[i])
  
  # save the new data frame
  saveRDS(df_usd, new_name)
}
```

```{r}
# P2: retrieve forex with yfR
from_currency <- c("HKD", "KRW", "GBP")
tickers_forex <- paste0(from_currency, "USD=X")

df_forex <- yf_get(
  tickers = tickers_forex,
  first_date = first_date,
  last_date = last_date,
  thresh_bad_data = 0,
  freq_data = "daily",
  do_complete_data = TRUE,
  do_cache = TRUE,
  cache_folder = cache_folder
)

glimpse(df_forex)
```
