```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(janitor)
library(patchwork)

# 3 largest in market cap
file_paths <- c("../data/JNJ_yfR_2015-01-30_2025-09-08.rds",
                "../data/rds/AZN_USD_2015-01-30_2025-09-08.rds", 
                "../data/PFE_yfR_2015-01-30_2025-09-08.rds")
```

```{r}
# Function
cumret <- function(file_path) {
  # Read data
  df <- readRDS(file_path)

  price_close <- df$price_close
  ret <- price_close / dplyr::lag(price_close) -1
  cumret <- cumprod(1 + coalesce(ret, 0)) - 1

  # Preprocess
  df <- df %>%
    group_by(ref_date) %>%
    select(contains("ticker"), ref_date, price_close, volume, price_adjusted) %>%
    mutate(
      price_close = as.numeric(price_close),
      price_adjusted = as.numeric(price_adjusted),
      volume = as.numeric(volume)
    ) %>%
    arrange(ref_date) %>%
    mutate(
      ret = !!ret,
      cumret = !!cumret)
  
  min_cumret <- min(df$cumret)
  ticker_col <- names(df)[grepl("ticker", names(df))]
  ticker_name <- df[[ticker_col[1]]][1]
  
  # Return useful objects
  return(list(
    data = df,
    ret = ret,
    cumret = cumret
  ))
}
```

```{r}
# combine data sets for stacked line chart
jnj_mod <- as.data.frame(cumret(file_paths[1])[[1]])
azn_mod <- as.data.frame(cumret(file_paths[2])[[1]])
pfe_mod <- as.data.frame(cumret(file_paths[3])[[1]])

combined_cumret <- bind_rows(jnj_mod, azn_mod, pfe_mod)
```

```{r}
# plot stacked line chart - general events
gen_events <- c(as.Date("2020-01-30"),
                as.Date("2020-12-31"),
                as.Date("2023-05-05"))

zoomed_combined <- combined_cumret %>%
  filter(
    ref_date >= min(gen_events) - 300, 
    ref_date <= max(gen_events) + 300
  )

minc <- min(combined_cumret$cumret)

p_ge <- ggplot(zoomed_combined, aes(x = ref_date, y = cumret, group = ticker, color = ticker)) +
  geom_line() +
  geom_vline(
    xintercept = gen_events,
    colour = "gray30",
    linetype = "dashed"
    ) +
  annotate(
    "label",
    x = gen_events[1],
    y = 0.55,
    label = "PHEIC\nAnnounced",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = gen_events[2],
    y = 0.7,
    label = "First FDA\nApproval",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = gen_events[3],
    y = 0.8,
    label = "PHEIC\nRemoved",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  labs(
    title = "Cumulative Returns of JNJ, AZN, and PFE",
    colour = "Ticker",
    x = "Date",
    y = "Cumulative returns since 2015-01-30"
  ) +
  theme_linedraw()
p_ge

ggsave("../output/cumret_genevents_3.png", plot = p_ge)
```

```{r}
# singular events
jnj <- as.Date(c(
  "2020-07-10",  # Phase 1/2 trial start
  "2021-02-27",  # US FDA emergency use
  "2021-04-13"   # (e.g. pause or related event)
))

pfe_events <- as.Date(c(
  "2020-11-01",  # Strong Phase 3 results + UK emergency use
  "2021-08-23",  # First COVID-19 vaccine approved by FDA (bullish then bearish)
  "2021-10-29"   # FDA emergency use for age 5–11 (bullish)
))

azn_events <- as.Date(c(
  "2020-04-23",  # Trials start worldwide (maybe 10-day event window)
  "2020-09-06",  # US trials halt (bearish)
  "2020-10-23",  # US trials resume (bullish)
  "2021-03-07",  # First case of blood clots
  "2021-03-16"   # More cases of blood clots
))

zoomed_jnj <- jnj_mod %>%
  filter(
    ref_date >= min(jnj_events) - 60, 
    ref_date <= max(jnj_events) + 60
  )

zoomed_azn <- azn_mod %>%
  filter(
    ref_date >= min(azn_events) - 60, 
    ref_date <= max(jnj_events) + 60
  )

zoomed_pfe <- pfe_mod %>%
  filter(
    ref_date >= min(pfe_events) - 60, 
    ref_date <= max(pfe_events) + 60
  )
```

```{r}
# plot jnj
p_jnj <- ggplot(zoomed_jnj, aes(x = ref_date, y = cumret)) +
  geom_line() +
  geom_vline(
    xintercept = jnj_events,
    colour = "gray30",
    linetype = "dashed"
    ) +
  annotate(
    "label",
    x = jnj_events[1],
    y = 0.5,
    label = "Phase 1/2\ntrial start",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = jnj_events[2],
    y = 0.67,
    label = "FDA EUA",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = jnj_events[3],
    y = 0.67,
    label = "Blood Clots",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  labs(
    title = "Cumulative Returns of JNJ",
    x = "Date",
    y = "Cumulative returns since 2015-01-30"
  ) +
  theme_linedraw()

p_jnj

ggsave("../output/cumret_jnj_events.png", plot = p_ge)
```

```{r}
# plot azn
p_azn <- ggplot(zoomed_azn, aes(x = ref_date, y = cumret)) +
  geom_line() +
  geom_vline(
    xintercept = azn_events,
    colour = "gray30",
    linetype = "dashed"
    ) +
  annotate(
    "label",
    x = azn_events[1],
    y = 0.28,
    label = "World Trials\nCommence",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = azn_events[2],
    y = 0.4,
    label = "US Trials\nhalt",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = azn_events[3],
    y = 0.35,
    label = "US Trials\nResume",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = azn_events[4],
    y = 0.33,
    label = "First Clots",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = azn_events[5],
    y = 0.4,
    label = "More Clots",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  labs(
    title = "Cumulative Returns of AZN",
    x = "Date",
    y = "Cumulative returns since 2015-01-30"
  ) +
  theme_linedraw()

p_azn

ggsave("../output/cumret_azn_events.png", plot = p_ge)
```

```{r}
# plot pfe
p_pfe <- ggplot(zoomed_pfe, aes(x = ref_date, y = cumret)) +
  geom_line() +
  geom_vline(
    xintercept = pfe_events,
    colour = "gray30",
    linetype = "dashed"
    ) +
  annotate(
    "label",
    x = pfe_events[1],
    y = 0.28,
    label = "UK EUA",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = pfe_events[2],
    y = 0.7,
    label = "FDA Approval",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  annotate(
    "label",
    x = pfe_events[3],
    y = 0.7,
    label = "FDA EUA\nfor Y5-11",
    angle = 0,
    vjust = -0.5,
    size = 3,
    colour = "gray30"
  ) +
  labs(
    title = "Cumulative Returns of PFE",
    x = "Date",
    y = "Cumulative returns since 2015-01-30"
  ) +
  theme_linedraw()

p_pfe

ggsave("../output/cumret_pfe_events.png", plot = p_pfe)
```
